# -*- coding: utf-8 -*-
"""train_and_evaluate.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SHqID7plggyX8WzPdjnsSR7bLw8cY31u
"""

"""
train_and_evaluate.py
---------------------

Module dùng để:
1. Giải phóng bộ nhớ GPU.
2. Huấn luyện mô hình YOLOv8x-pose bằng Ultralytics CLI.
3. Đọc kết quả training từ results.csv và tìm epoch tốt nhất (Pose mAP50).
4. Đánh giá mô hình best.pt trên tập test.

Yêu cầu:
- Đã chạy concat_datasets.py hoặc giải nén file zip trong data/image để tạo merged/data.yaml.
- Đã cài: ultralytics, torch, pandas, opencv-python.

Chạy:
    python train_and_evaluate.py
"""

from ultralytics import YOLO
import torch
import pandas as pd
import subprocess
import os


def clear_gpu():
    """
    Giải phóng bộ nhớ GPU để tránh lỗi CUDA Out Of Memory.
    """
    try:
        torch.cuda.empty_cache()
        print("🔄 GPU memory cleared.")
    except:
        print("⚠️ Không tìm thấy GPU hoặc không thể clear cache.")


def run_training(data_path: str, model_path: str):
    """
    Chạy huấn luyện YOLO bằng subprocess.

    Args:
        data_path (str): Đường dẫn đến file data.yaml của YOLO.
        model_path (str): Mô hình pretrain (vd: yolov8x-pose.pt).

    Returns:
        None
    """

    command = [
        "yolo",
        "task=pose",
        "mode=train",
        f"model={model_path}",
        f"data={data_path}",
        "batch=16",
        "epochs=150",
        "imgsz=640",
        "mosaic=0.0",
        "plots=True",
        "lr0=0.001",
        "lrf=0.0001",
        "weight_decay=0.0005",
        "amp=True",
        "resume=True"
    ]

    print("🚀 Bắt đầu huấn luyện YOLOv8x-pose...")
    subprocess.run(" ".join(command), shell=True)
    print("✅ Huấn luyện hoàn tất!")


def find_best_epoch(csv_path: str) -> pd.Series:
    """
    Đọc results.csv và tìm epoch có Pose mAP50 cao nhất.

    Args:
        csv_path (str): Đường dẫn đến file results.csv.

    Returns:
        pd.Series: Dòng chứa epoch tốt nhất.
    """

    df = pd.read_csv(csv_path)

    # Epoch tốt nhất dựa trên metrics/mAP50(P)
    best_epoch = df.loc[df['metrics/mAP50(P)'].idxmax()]
    return best_epoch


def evaluate_model(best_weight_path: str, data_path: str):
    """
    Đánh giá mô hình tốt nhất trên test set.

    Args:
        best_weight_path (str): Đường dẫn file best.pt.
        data_path (str): Đường dẫn file data.yaml.

    Returns:
        dict: Chỉ số Box mAP50 và Pose mAP50.
    """
    print("🧪 Đang đánh giá mô hình best.pt...")

    model = YOLO(best_weight_path)
    metrics = model.val(data=data_path, split="test")

    return {
        "box_mAP50": metrics.box.map50,
        "pose_mAP50": metrics.pose.map50
    }


if __name__ == "__main__":
    # ---- 1. Clear GPU ----
    clear_gpu()

    # ---- 2. Cấu hình đường dẫn ----
    DATA_PATH = "datasets/YOLO_Datasets/merged/data.yaml"
    MODEL_PRETRAIN = "yolov8x-pose.pt"

    # ---- 3. Train YOLO ----
    run_training(DATA_PATH, MODEL_PRETRAIN)

    # ---- 4. Đọc kết quả và chọn epoch tốt nhất ----
    results_csv = "./runs/pose/train/results.csv"
    best_epoch = find_best_epoch(results_csv)

    print("\n🏆 Epoch tốt nhất (chọn theo Pose mAP50):")
    print(best_epoch)

    # ---- 5. Đánh giá mô hình best.pt ----
    BEST_WEIGHT = "./runs/pose/train/weights/best.pt"
    eval_results = evaluate_model(BEST_WEIGHT, DATA_PATH)

    print("\n📊 Kết quả đánh giá:")
    print(f"Box mAP50   : {eval_results['box_mAP50']}")
    print(f"Pose mAP50  : {eval_results['pose_mAP50']}")