# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vlkOxKK6ydfx0QxO9WgZCKebKxuiMSfO
"""

"""
EvaluationModels.py
-------------------

Module này dùng để:
1. Giải nén dataset (nếu cần).
2. Kiểm tra số lượng file ảnh/nhãn.
3. Chạy đánh giá (evaluation) cho nhiều mô hình YOLO:
   - Player detection model
   - Pitch nano model
   - Pitch small model
   - Các pitch models khác tùy vào đường dẫn cung cấp

Hệ thống sẽ tự động:
- Load mô hình
- Chạy model.val() trên tập test
- In ra Box mAP50, Box mAP50-95, Pose mAP50, Pose mAP50-95

Yêu cầu:
- ultralytics
- opencv-python
- torch
- pandas
"""

import os
from pathlib import Path
from ultralytics import YOLO
import torch


# ----------------------------------------------------------
# 1. Utility – đếm file trong thư mục
# ----------------------------------------------------------

def count_files(root_dir: str) -> int:
    """Đếm tổng số file trong một thư mục."""
    path = Path(root_dir)
    if not path.exists():
        print(f"❌ Thư mục không tồn tại: {root_dir}")
        return 0
    return sum(1 for p in path.rglob("*") if p.is_file())


def count_jpg(root_dir: str) -> int:
    """Đếm số file .jpg hoặc .jpeg trong thư mục."""
    path = Path(root_dir)
    if not path.exists():
        print(f"❌ Không tồn tại thư mục: {root_dir}")
        return 0
    return sum(1 for p in path.rglob("*") if p.suffix.lower() in [".jpg", ".jpeg"])


# ----------------------------------------------------------
# 2. Evaluate function – dùng chung cho tất cả models
# ----------------------------------------------------------

def evaluate_model(model_path: str, data_yaml: str):
    """
    Đánh giá mô hình YOLO trên test set.

    Args:
        model_path (str): đường dẫn tới file .pt
        data_yaml (str): đường dẫn tới file data.yaml

    Returns:
        dict: chứa các mAP của Box và Pose
    """
    print(f"\n==============================")
    print(f"🔍 Đang đánh giá model: {model_path}")
    print(f"==============================")

    model = YOLO(model_path)

    metrics = model.val(
        data=data_yaml,
        split="test"
    )

    results = {
        "Box_mAP50": metrics.box.map50,
        "Box_mAP50_95": metrics.box.map,
        "Pose_mAP50": getattr(metrics, "pose", None).map50 if hasattr(metrics, "pose") else None,
        "Pose_mAP50_95": getattr(metrics, "pose", None).map if hasattr(metrics, "pose") else None
    }

    print(f"📌 Box mAP50      : {results['Box_mAP50']}")
    print(f"📌 Box mAP50-95   : {results['Box_mAP50_95']}")
    if results["Pose_mAP50"] is not None:
        print(f"📌 Pose mAP50     : {results['Pose_mAP50']}")
        print(f"📌 Pose mAP50-95  : {results['Pose_mAP50_95']}")

    return results


# ----------------------------------------------------------
# 3. Main – chạy lần lượt tất cả evaluations
# ----------------------------------------------------------

def main():
    """
    Hàm chính: kiểm tra dữ liệu → chạy evaluation cho các models.
    """

    # ==== 1. Kiểm tra số lượng file (tương đương Cell 31–32) ====
    train_folder = "/content/data/datasets/YOLO_Datasets/merged/images/train"
    print("📁 Số file tổng  :", count_files(train_folder))
    print("🖼️ Số file .jpg :", count_jpg(train_folder))

    # ==== 2. Cấu hình dataset YAML ====
    DATA_YAML = "/content/data/datasets/YOLO_Datasets/merged/data.yaml"

    # ==== 3. Danh sách model cần đánh giá ====
    model_paths = [
        "/content/best_pitch_nano.pt",
        "/content/best_pitch_s.pt"
    ]

    # ==== 4. Chạy evaluation từng mô hình ====
    for model_path in model_paths:
        if os.path.exists(model_path):
            evaluate_model(model_path, DATA_YAML)
        else:
            print(f"⚠️ Model không tồn tại: {model_path}")


# ----------------------------------------------------------
if __name__ == "__main__":
    main()